### ISSUE TITLE
Mark comment as outdated once conflict resolved

### ISSUE THREAD

**Issue by Josh-Cena** [eps1lon/actions-label-merge-conflict#101] opened 2023-02-13 18:09 UTC
When a big PR (e.g. a formatting PR like https://github.com/mdn/content/pull/24062) gets stalled for a while, a lot of duplicate comments pile up. It would be great if the comment can be minimized each time the conflict is resolved.

**Comment by eps1lon** [comment] 2023-02-13 19:22
Duplicate of https://github.com/eps1lon/actions-label-merge-conflict/issues/40

**Closed by eps1lon** 2023-02-13 19:22 UTC
